/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OligarchFari } from "./OligarchFari";
export { OligarchFari__factory } from "./OligarchFari__factory";
